# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python27:
      python.version: '2.7'
  maxParallel: 1

steps:
- task: UsePythonVersion@0
  inputs:
   versionSpec: '$(python.version)'
   architecture: 'x64'
  displayName: 'Use Python $(python.version)'

- script: pip install robotframework robotframework-selenium2library robotframework-excellibrary && npm install geckodriver
  displayName: 'Install dependencies'

- powershell: robot --pythonpath . -x outputxunit.xml Tests/firefox.robot
  displayName: 'Run Robot Tests'

- task: PublishTestResults@1
  inputs:
   testResultsFiles: outputxunit.xml
   searchFolder: 'D:\a\1\s\'
  condition: succeededOrFailed()
  displayName: 'Publish Test Results outputxunit.xml'
   


   

